### ISSUE TITLE
About the data path

### ISSUE THREAD

**Issue by RyanQR** [licongguan/ILM-ASSL#6]
I noticed that when you use Dataloader in your code, you use cfg["data_list"] directly. In fact, there are two data_lists in cfg, how do you make sure that you are loading the correct list? Also, there are misspellings of variables in your published code, have you ever run your published code?

**Comment by licongguan** [comment]
Please refer to the training steps in README: 

```
cd experiments/gtav2cityscapes/1.0%

sh train.sh <num_gpu> <port>
```

For example, see **ILM-ASSL/experiments/gtav2cityscapes/1.0%/config.yaml** file. 

The fifth line sets `data_list: /data1/glc/ILM-ASSL-master/data/gtav2cityscapes/1.0%/labeled.txt`

Also, we ran the posted code and it worked fine.
